### Mock MPESA B2B API (via wiremock)
POST http://127.0.0.1:8080/mpesa/b2b/v1/remittax

{}

### Initiate MPESA B2B payment
POST http://127.0.0.1:5000/api/v1.0/payment/initiate
Content-Type: application/json

{
  "Amount": "50",
  "pnr": "56yR533"
}

### Confirm MPESA B2B payment
POST http://127.0.0.1:5000/api/v1.0/payment/confirm
Content-Type: application/json

{
  "Result": {
    "ResultType": 0,
    "ResultCode": 0,
    "ResultDesc": "The service request is processed successfully.",
    "OriginatorConversationID": "1247_2348",
    "ConversationID": "AG_201_88531",
    "TransactionID": "NLJ41HAY6Q",
    "ResultParameters": {
      "ResultParameter": [
        {
          "Key": "TransactionAmount",
          "Value": 10
        },
        {
          "Key": "TransactionReceipt",
          "Value": "NLJ41HAY6Q"
        },
        {
          "Key": "B2CRecipientIsRegisteredCustomer",
          "Value": "Y"
        },
        {
          "Key": "B2CChargesPaidAccountAvailableFunds",
          "Value": -4510.00
        },
        {
          "Key": "ReceiverPartyPublicName",
          "Value": "254708374149 - John Doe"
        },
        {
          "Key": "TransactionCompletedDateTime",
          "Value": "19.12.2019 11:45:50"
        },
        {
          "Key": "B2CUtilityAccountAvailableFunds",
          "Value": 10116.00
        },
        {
          "Key": "B2CWorkingAccountAvailableFunds",
          "Value": 900000.00
        }
      ]
    },
    "ReferenceData": {
      "ReferenceItem": {
        "Key": "QueueTimeoutURL",
        "Value": "https:\/\/internalsandbox.safaricom.co.ke\/mpesa\/b2cresults\/v1\/submit"
      }
    }
  }
}

### Timeout MPESA B2B Payment
POST http://127.0.0.1:5000/api/v1.0/payment/confirm
Content-Type: application/json

{
  "Result": {
    "ResultType": 0,
    "ResultCode": 2001,
    "ResultDesc": "The initiator information is invalid.",
    "OriginatorConversationID": "4734_5007",
    "ConversationID": "AG_095_33231",
    "TransactionID": "NLJ0000000",
    "ReferenceData": {
      "ReferenceItem": {
        "Key": "QueueTimeoutURL",
        "Value": "https:\/\/internalsandbox.safaricom.co.ke\/mpesa\/b2cresults\/v1\/submit"
      }
    }
  }
}